### ISSUE TITLE
How to un-tag canned actions?

### ISSUE THREAD

**Issue by fkusei** [bundlewrap/bundlewrap#687] opened 2021-11-15 09:18 UTC
Consider the following definition:
```python
svc_systemd = {
    'nginx': {
        'needs': {
            'pkg_apt:nginx',
        },
        'tags': {
            'causes-downtime'
        },
    },
}

files['/etc/nginx/ssl/some.crt.pem'] = {
    'triggers': {
        'svc_systemd:nginx:reload',
    },
}

```

We do regularly apply all our systems using `bw apply -s tag:causes-downtime`, which happily deploys certificates, but won't reload nginx, because the systemd unit has `tag:causes-downtime`. One could define an `action` item to reload nginx, but that sounds wrong to me. Maybe we should be able to trigger a reload regardless of the tag? I'm not sure on how to archive this though.

**Comment by trehn** [comment] 2021-11-15 11:33
It doesn't inherit the tag (yet... #599), but it probably gets skipped because the canned action uses a 'needs' dep on the service. Which kind of makes sense, because the service needs to run in order to be able to reload.

I guess what you actually want to do here is tag the _restart_, not the service itself, making this a duplicate of #560.

**Closed by trehn** 2021-11-15 11:33 UTC
