### ISSUE TITLE
svc_systemd throws exception when the service is in failed state

### ISSUE THREAD

**Issue by ettoredn** [bundlewrap/bundlewrap#271] opened 2016-08-12 16:18 UTC
I'm using 2.7.1 and experiencing the following problem with svc_systemd:

```
svc_systemd = {
    'php7.0-fpm': {},
}
```

results in the following when php7.0-fpm is in failed state:

```
# bw apply
[..]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/__init__.py", line 66, in wrapper
    return f(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/__init__.py", line 155, in main
    for line in output:
  File "/Library/Python/2.7/site-packages/bundlewrap/cmdline/apply.py", line 80, in bw_apply
    worker_pool.run()
  File "/Library/Python/2.7/site-packages/bundlewrap/concurrency.py", line 150, in run
    traceback = "".join(format_tb(exc.__traceback__))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 76, in format_tb
    return format_list(extract_tb(tb, limit))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 95, in extract_tb
    f = tb.tb_frame
AttributeError: 'list' object has no attribute 'tb_frame'
```

Service php7.0-fpm status

```
#  systemctl status php7.0-fpm
● php7.0-fpm.service - The PHP 7.0 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.0-fpm.service; enabled)
   Active: failed (Result: exit-code) since Fri 2016-08-12 18:15:06 CEST; 1min 53s ago
     Docs: man:php-fpm7.0(8)
  Process: 19403 ExecStart=/usr/sbin/php-fpm7.0 --nodaemonize --fpm-config /etc/php/7.0/fpm/php-fpm.conf (code=exited, status=78)
 Main PID: 19403 (code=exited, status=78)
```

If I remove the svc_systemd entry, everything works fine.

**Comment by trehn** [comment] 2016-08-13 07:17
There's two problems here: The AttributeError you're seeing is a bug in BundleWrap when running under Python 2. Underneath that is the actual exception that is being hidden by the AttributeError. While I look into the first issue, can you try running BundleWrap with Python 3 to get the actual exception?

**Comment by trehn** [comment] 2016-12-23 01:04
can't reproduce, closing until real exception is reported

**Closed by trehn** 2016-12-23 01:04 UTC
